namespace Abo.Client.WP.Silverlight.Assets.Flags
{
    partial class CountriesList
    {
        public static string[] Countries = new[]
                                               {
                                                   "African Union",
                                                   "Argentina",
                                                   "Australia",
                                                   "Austria",
                                                   "Belarus",
                                                   "Belgium",
                                                   "Bosnia & Herzegovina",
                                                   "Brazil",
                                                   "Bulgaria",
                                                   "Canada",
                                                   "China",
                                                   "Croatia",
                                                   "Czech Republic",
                                                   "Denmark",
                                                   "Egypt",
                                                   "England",
                                                   "Estonia",
                                                   "Finland",
                                                   "France",
                                                   "Germany",
                                                   "Greece",
                                                   "Hungary",
                                                   "Iceland",
                                                   "India",
                                                   "Indonezia",
                                                   "Iran",
                                                   "Iraq",
                                                   "Ireland",
                                                   "Israel",
                                                   "Italy",
                                                   "Japan",
                                                   "Kazakhstan",
                                                   "Latvia",
                                                   "Lithuania",
                                                   "Luxembourg",
                                                   "Malta",
                                                   "Mexico",
                                                   "Moldova",
                                                   "Monaco",
                                                   "Morocco",
                                                   "Netherlands",
                                                   "New Zealand",
                                                   "North Korea",
                                                   "Northern Ireland",
                                                   "Norway",
                                                   "Poland",
                                                   "Portugal",
                                                   "Romania",
                                                   "Russia",
                                                   "Saint Lucia",
                                                   "Slovakia",
                                                   "Slovenia",
                                                   "South Korea",
                                                   "Spain",
                                                   "Sweden",
                                                   "Switzerland",
                                                   "Turkey",
                                                   "Ukraine",
                                                   "United Kingdom",
                                                   "United States",
                                               };
    }
}
