//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abo.Client.WP.Silverlight.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Abo.Client.WP.Silverlight.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASTRAL BATTLES ONLINE.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        public static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed, it seems that your account is no longer exists, would you like to create a new one?.
        /// </summary>
        public static string AuthenticationFailedAccountDoesntExists {
            get {
                return ResourceManager.GetString("AuthenticationFailedAccountDoesntExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data is invalid.
        /// </summary>
        public static string DataIsInvalid {
            get {
                return ResourceManager.GetString("DataIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device is banned..
        /// </summary>
        public static string DeviceIsBanned {
            get {
                return ResourceManager.GetString("DeviceIsBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name or password..
        /// </summary>
        public static string InvalidNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is already in use.
        /// </summary>
        public static string IsAlreadyInUse {
            get {
                return ResourceManager.GetString("IsAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not moderator anymore.
        /// </summary>
        public static string IsNotModerAnymore {
            get {
                return ResourceManager.GetString("IsNotModerAnymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is now moderator.
        /// </summary>
        public static string IsNowModer {
            get {
                return ResourceManager.GetString("IsNowModer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a messsage:.
        /// </summary>
        public static string SendAMessage {
            get {
                return ResourceManager.GetString("SendAMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is busy at the moment, try again later. We are sorry for the inconvenience..
        /// </summary>
        public static string ServerIsBusyAtTheMomentDesc {
            get {
                return ResourceManager.GetString("ServerIsBusyAtTheMomentDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shouldn&apos;t be empty.
        /// </summary>
        public static string ShouldntBeEmpty {
            get {
                return ResourceManager.GetString("ShouldntBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string SystemNick {
            get {
                return ResourceManager.GetString("SystemNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to too large.
        /// </summary>
        public static string TooLarge {
            get {
                return ResourceManager.GetString("TooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to too small.
        /// </summary>
        public static string TooSmall {
            get {
                return ResourceManager.GetString("TooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your version is out of date, please, update it..
        /// </summary>
        public static string VersionIsOutOfDate {
            get {
                return ResourceManager.GetString("VersionIsOutOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to banned.
        /// </summary>
        public static string XbannedY {
            get {
                return ResourceManager.GetString("XbannedY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to devoiced.
        /// </summary>
        public static string XdevoicedY {
            get {
                return ResourceManager.GetString("XdevoicedY", resourceCulture);
            }
        }
    }
}
